### ISSUE TITLE
Use of Project Title (or external GUID) as identifier when Basecamp Project ID is not yet available

### ISSUE THREAD

**Issue by big-data-labs** [basecamp/bcx-api#181]
We need to attach images simultaneous to submitting a new Basecamp project (using CognitoForms with Zapier).  How can we fetch the ID of the new project?  (Zapier has informed us this is not possible since apparently the Basecamp API requires the ID of the new project.)

We also need to append an incremental number to the title, with a unique number seed based on the project name.  We could pull this incremental number from a Google spreadsheet, but apparently we have no way to use the Basecamp API to make the title change since we don't have the ID of the new project.

Is it possible to submit updates through the API using the project title as our unique identifier?

**Comment by eileencodes** [comment]
Hi @big-data-labs!

There is no way to attach images to a Basecamp project without the project existing. There's simply nothing to attach it to if you don't have a project.

You could create the project with the API (test/controller/test_case_test.rb) which would return the ID then attach the images. The other reason this isn't possible in one request is because attachment creation and project creation are 2 different API endpoints. We don't plan on adding an endpoint that combines them.

Let me know if I misunderstood your question. Thanks for using Basecamp! :smile:

**Comment by big-data-labs** [comment]
Is it possible to fetch a project's ID using it's title (or another attribute)?
Is it possible to insert an external GUID or other unique ID with the new project post?

**Comment by eileencodes** [comment]
> Is it possible to fetch a project's ID using it's title (or another attribute)?

No, sorry, the endpoint requires an ID. `GET /projects/1.json`. The only other way would be to fetch all projects and iterate through to find your unique identifier other than title

> Is it possible to insert an external GUID or other unique ID with the new project post?

You can insert it as part of the title, but no there is not an extra attribute for this purpose. You could also use the description attribute for this if you prefer.
